# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['ClassLively.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resource', 'resource'),
        ('font', 'font'),
        ('data', 'data'),
        ('config.py', '.'),
        ('constants.py', '.'),
        ('logger.py', '.'),
        ('setting.py', '.'),
        ('city_selector.py', '.'),
        ('version.py', '.'),
    ],
    hiddenimports=[
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtWidgets',
        'PyQt5.QtGui',
        'qfluentwidgets',
        'requests',
        'cnlunar',
        'sqlite3',
        'json',
        'platform',
        'ctypes',
        'shutil',
        'datetime',
        'winreg',
        'logging',
        'logging.handlers',
        'inspect',
        'qfluentwidgets.FluentIcon',
        'qfluentwidgets.qconfig',
        'qfluentwidgets.QConfig',
        'qfluentwidgets.ConfigItem',
        'qfluentwidgets.OptionsConfigItem',
        'qfluentwidgets.BoolValidator',
        'qfluentwidgets.ColorConfigItem',
        'qfluentwidgets.OptionsValidator',
        'qfluentwidgets.RangeConfigItem',
        'qfluentwidgets.RangeValidator',
        'qfluentwidgets.ConfigSerializer',
        'qfluentwidgets.Theme',
        'qfluentwidgets.SettingCardGroup',
        'qfluentwidgets.OptionsSettingCard',
        'qfluentwidgets.ScrollArea',
        'qfluentwidgets.ExpandLayout',
        'qfluentwidgets.Theme',
        'qfluentwidgets.isDarkTheme',
        'qfluentwidgets.CustomColorSettingCard',
        'qfluentwidgets.SwitchSettingCard',
        'qfluentwidgets.RangeSettingCard',
        'qfluentwidgets.LineEdit',
        'qfluentwidgets.SettingCard',
        'qfluentwidgets.ComboBoxSettingCard',
        'qfluentwidgets.SpinBox',
        'qfluentwidgets.PushButton',
        'qfluentwidgets.MessageBoxBase',
        'qfluentwidgets.SearchLineEdit',
        'qfluentwidgets.ListWidget',
        'qfluentwidgets.SubtitleLabel',
        'qfluentwidgets.BodyLabel',
        'qfluentwidgets.InfoBar',
        'PyQt5.QtCore.QLocale',
        'PyQt5.QtCore.QTranslator',
        'PyQt5.QtCore.QUrl',
        'PyQt5.QtCore.QTimer',
        'PyQt5.QtCore.Qt',
        'PyQt5.QtCore.QTime',
        'PyQt5.QtCore.QDate',
        'PyQt5.QtWidgets.QApplication',
        'PyQt5.QtWidgets.QWidget',
        'PyQt5.QtWidgets.QSystemTrayIcon',
        'PyQt5.QtWidgets.QMenu',
        'PyQt5.QtWidgets.QAction',
        'PyQt5.QtWidgets.QLabel',
        'PyQt5.QtWidgets.QPushButton',
        'PyQt5.QtWidgets.QVBoxLayout',
        'PyQt5.QtWidgets.QHBoxLayout',
        'PyQt5.QtWidgets.QGridLayout',
        'PyQt5.QtWidgets.QSpacerItem',
        'PyQt5.QtWidgets.QSizePolicy',
        'PyQt5.QtWidgets.QFileDialog',
        'PyQt5.QtWidgets.QGraphicsBlurEffect',
        'PyQt5.QtWidgets.QStackedLayout',
        'PyQt5.QtGui.QFontDatabase',
        'PyQt5.QtGui.QFont',
        'PyQt5.QtGui.QIcon',
        'PyQt5.QtGui.QPixmap',
        'PyQt5.QtGui.QImage',
        'PyQt5.QtGui.QPainter',
        'PyQt5.QtGui.QColor',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ClassLively',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resource/icons/CY.png',
)
